### ISSUE TITLE
Does "midtrans.min.js" stable?

### ISSUE THREAD

**Issue by XuHanpeace** [veritrans/veritrans.github.io#106]
I want to copy the source code to my local project instead of use <script> tag, and....can provied uncompressed **midtrans.min.js**?

**Comment by rizdaprasetya** [comment]
hi @XuHanpeace that is not recommended.
You should always use hosted/online version of `midtrans.min.js` to ensure you always have the latest working version of the library.
using local asset might break things if in the future Midtrans do any changes on the API.
Please keep using `<script>` tag

**Comment by XuHanpeace** [comment]
@rizdaprasetya 
Thanks for your reply, I'll use <script> tag, and this issue can be closed
