### ISSUE TITLE
get pricing transaction by payment mothod

### ISSUE THREAD

**Issue by baihaqyaviq** [veritrans/veritrans.github.io#112]
bagaimana mendapatkah harga transaksi sesuai metode pembayaran yang dilakukan user, rencana untuk menambahkan biaya transaksi ke user (harga barang + biaya transaksi)

**Comment by rizdaprasetya** [comment]
Hi @baihaqyaviq 
Untuk perihal biaya per metode pembayaran silahkan dihitung sendiri dari sisi sistem anda, selaku merchant, berdasarkan harga pada agreement bisnis. Karena memang pada dasarnya biaya tersebut adalah MDR -Merchant Discount Rate- yg dibebankan ke merchant, tidak untuk dibebankan langsung ke customer. Tapi sebagai Merchant boleh menghitung sendiri, hal tersebut mengikuti regulasi yg ada.

Terima kasih.

**Comment by baihaqyaviq** [comment]
baik terimakasih, atas responsenya
