### ISSUE TITLE
[ASK] Dummy Product Code for Alfamart Simulator

### ISSUE THREAD

**Issue by koyanyaroo** [veritrans/veritrans.github.io#131]
Hi, 

In order to test my Snap Payment using Alfamart ([simulator here](https://simulator.sandbox.midtrans.com/alfamart/index))

How do I fill the `Alfamart merchant code + alfamart sub merchant code`

Thanks,

**Comment by mister-ard97** [comment]
have you get a payment code from your test?

**Comment by koyanyaroo** [comment]
Yes, I got the payment code, and I've already put that on `payment code` input form, but when I submit i got 
>Internal Server Error: 11

**Comment by rizdaprasetya** [comment]
Hi @mister-ard97  @koyanyaroo 
You can fill the `Alfamart merchant code + alfamart sub merchant code`
with number on your `merchant id`, so for example if your Merchant ID is `G230781802`, the value you can use is `230781802`

To get Merchant ID, go to `Dashboard > Settings > Access Keys`

For now that process is a bit complicated. We are currently improving the way to test Alfamart transaction on Sandbox.

**Comment by koyanyaroo** [comment]
Thank you it's all done now
