### ISSUE TITLE
Links inside specification

### ISSUE THREAD

**Issue by Paxa** [veritrans/veritrans.github.io#35]
On this page http://docs.veritrans.co.id/sandbox/charge.html#specification

I think it would be more useful if add links inside page, for example when we click "customer_details" it goes to section with full info.

![screen shot 2015-02-19 at 21 40 19](https://cloud.githubusercontent.com/assets/26019/6268593/abb07aaa-b880-11e4-9a62-305fbc40e5d6.png)

Click blue "customer_details" and it goes to:

![screen shot 2015-02-19 at 21 41 04](https://cloud.githubusercontent.com/assets/26019/6268595/ace945fa-b880-11e4-8aaf-fa690d4eef1b.png)

**Comment by yocki-s** [comment]
already implement in new design
