### ISSUE TITLE
Fancy Box not compatible

### ISSUE THREAD

**Issue by duniadua** [veritrans/veritrans.github.io#37]
Hi, im using VT Direct and copy paste the example from Github, but unfortunately the Fancybox library was not run. (the OTP Page not show), and can u add example for Fancybox alternative which can we use instead of Fancy Box

**Comment by Paxa** [comment]
Do you use php or ruby library? What js library you want to use instead fancybox? We will provide example

**Comment by duniadua** [comment]
Im using PHP library, can u provide the example for JqueryUI https://jqueryui.com/dialog/ many thanks

**Comment by Paxa** [comment]
You can see example in my fork https://github.com/Paxa/veritrans-php/commit/a73243df9c84e7abdc43c0285c5f6b0e106b6a42 ([download as zip](https://github.com/Paxa/veritrans-php/archive/a73243df9c84e7abdc43c0285c5f6b0e106b6a42.zip))

I run it as:
```
cd veritrans-php/examples/vt-direct
php -S 127.0.0.1:4000
```
open http://localhost:4000/checkout.php in browser
