### ISSUE TITLE
additional cost

### ISSUE THREAD

**Issue by anharfadly** [veritrans/veritrans.github.io#40]
Is there any way to add some additional cost?

**Comment by Paxa** [comment]
@anharfadly For transaction? Using Vt-Web or Vt-Direct?

**Comment by anharfadly** [comment]
Yes, using VT-Web

**Comment by yocki-s** [comment]
Hi @anharfadly 

What additional cost you mean?
Discount, shipping fee??

We recommend you to use item parameter for discount/voucher when send the data to Veritrans.

Example :
Item price / Price = 100.000
Voucher / Item = -50.000
Gross Amount = 50.000

**Comment by anharfadly** [comment]
OK thanks
