### ISSUE TITLE
API for check balance and auto create virtual account for VT-direct

### ISSUE THREAD

**Issue by eka83838** [veritrans/veritrans.github.io#45]
if available API to check balance and to show our deposit in Veritrans? In addition, if available APIs to create auto generate virtual account?

**Comment by Paxa** [comment]
Currently we don't have API for billing information.

> APIs to create auto generate virtual account

Could you please explain in more details what do you want to use it for?

**Comment by rizdaprasetya** [comment]
> APIs to create auto generate virtual account
Currently you can't directly generate VA (virtual account) using API.
But this could be achieved by using our VT-Direct feature, basically you can call API to do bank transfer charge, the response will include the generated VA number.
Please refer to this docs:
http://docs.veritrans.co.id/en/vtdirect/integration_va.html

**Comment by eka83838** [comment]
> APIs to create auto generate virtual account

Okay, thank you very much for the information, this issue is already clear.

> APIs to check customers balance

A case in point, my customer has a deposit balance of 1 million, he wants to top up a deposit of 1 million, the plan I will use the VT direct to transfer, when the status of the transaction is settlement, then I want the balance of deposit customers are regularly updated to 2 million without having admin manually update the balance of the deposit.
Is there an API that handles it auto update the account balance?

**Comment by rizdaprasetya** [comment]
I see,
So the scenario is: Your customer would be able to do top up, and each customer will have different account balance, is that correct?
This scenario would is possible to be implemented, infact some of our merchant also using this kind of scenario. But, for each customer balance need to be stored on your own server, the customer's account/balance logic & data is stored on your own server.

For example, this is what you need to implement in your side:

> - Customer A register (set balance = 0) -> Do topup 200.000, pay using VT Direct, payment success -> Veritrans will send HTTP Post notification (update balance to +200.000 for customer A)
> - Customer B register (set balance = 0) -> Do topup 150.000, pay using VT Direct, payment success -> Veritrans will send HTTP Post notification (update balance to +150.000 for customer B)

This is what will be recorded in your Veritrans Account for example:
> - Customer A do success payment with amount of 200.000
> - Customer B do success payment with amount of 150.000
> - Your total transaction is 350.000

Note that all the balance for each customer need to be stored on your own server.

> Is there an API that handles it auto update the account balance?

For every success transaction, we will send automated HTTP POST notification to your server, so your server could update balance automatically

> And I will do this VT integration, using node.js, if it works well?

Yes, it's possible to integrate using Node.JS, but unfortunately we don't have sample code in Node.JS, as long as you understand how to do API Call (REST) you will be able to do that in Node.JS
Please refer to this API Docs, for further details:
http://docs.veritrans.co.id/en/api/introduction.html

**Comment by eka83838** [comment]
> 
- Customer A register (set balance = 0) -> Do topup 200.000, pay using VT Direct, payment success Veritrans will send HTTP Post notification (update balance to +200.000 for customer A)
- Customer B register (set balance = 0) -> Do topup 150.000, pay using VT Direct, payment success Veritrans will send HTTP Post notification (update balance to +150.000 for customer B)

if I use VT-direct, where HTTP POST notification will be sent?
To our servers?
If yes? how does Veritrans know the url for POST?

**Comment by rizdaprasetya** [comment]
> if I use VT-direct, where HTTP POST notification will be sent?
> To our servers?
> If yes? how does Veritrans know the url for POST?

To your server, to set where the POST will be sent, please login to your Veritrans Account, go to menu:
Settings > Configuration
FIll in the **Payment Notification URL**
