### ISSUE TITLE
Masalah approve status veritrans

### ISSUE THREAD

**Issue by Ramdhanismk10** [veritrans/veritrans.github.io#70]
Halo semuanya, saya mau nanya tentang approve status transaksi di veritrans. sebelumnya saya menggunakan kode berikut : 

public function approve($order_id)
{
	echo 'test get approve </br>';
	print_r ($this->veritrans->approve($order_id) );
}

Dan di library veritrans seperti ini : 

public static function approve($id)
  {
    	return Veritrans::post(
        Veritrans::getBaseUrl() . '/' . $id . '/approve',
        Veritrans::$serverKey,
        false)->status_code;
  }

Namun terjadi error, : 
![image](https://cloud.githubusercontent.com/assets/5095341/21001150/5cfdc520-bd51-11e6-8039-ec247d5a751f.png)

An uncaught Exception was encountered

Type: Exception

Message: Veritrans Error (500): Sorry our system has experienced an internal error, we will fix it as soon as possible

Filename: C:\xampp\htdocs\myprojectextend\veritrans\application\libraries\Veritrans.php

Line Number: 124

Apa ada yang bisa bantu saya ??? 
sebelumnya terima kasih....

**Comment by rizdaprasetya** [comment]
Halo,

Apakah ada order ID / Transaction ID yang digunakan? akan dicek melalui log API

Untuk response pertanyaan yang lebih cepat, kami sarankan anda mengirim email ke support@midtrans.com
