### ISSUE TITLE
Custom expiry date based on payment method

### ISSUE THREAD

**Issue by yafithekid** [veritrans/veritrans.github.io#71]
Hi, I read the docs for **vtweb** here 
[https://docs.midtrans.com/en/api/methods.html#vtwebcharge](https://docs.midtrans.com/en/api/methods.html#vtwebcharge) and here [https://docs.midtrans.com/en/api/methods.html#Set-Custom-Expiry](https://docs.midtrans.com/en/api/methods.html#Set-Custom-Expiry)
AFAIK I can set the expiry date based on `custom_expiry`.

I have a use case that different `enabled_payments` use different expiry days. For example, using ATM Permata, the expiry days is 3 days and Mandiri, the expiry days is 1 day. Can you give explanation how to do it?

**Comment by rizdaprasetya** [comment]
Hi @yafithekid ,

Yes you can set the expiry date based on `custom_expiry`.

To better suit your usecase, you should do API call (request payment url) **after your customer select which payment method** they want, then you know what expiry duration you should send as `custom_expiry` parameter, along with that you can send the `enabled_payments` parameter according to the payment method chosen by customer.

For example: 
- Customer choose Permata, send `custom_expiry` as 3 days and `enabled_payments` as `permata_va`
- Customer choose MandiriBill Payment, send `custom_expiry` as 3 days and `enabled_payments` as `echannel` (alias for Mandiri Bill)

Sorry for late reply, for faster response you better send your questions to:
support@midtrans.com

**Comment by yafithekid** [comment]
Hi @rizdaprasetya. Thanks for the response.

It would be nice if `custom_expiry` in `vtweb` can be set based on the `payment` method. For next feature maybe?

**Comment by rizdaprasetya** [comment]
Thanks for your feedback and concern. Our team will consider this feature. But for near future this feature won't be available yet.
