### ISSUE TITLE
Notifikasi untuk Overlimit & Saldo Tidak Mencukupi.

### ISSUE THREAD

**Issue by bestgoodz** [veritrans/veritrans.github.io#72]
Di Document tidak ada penjelasan untuk notifikasi/result message jika Credit Card si user Overlimit dan/atau e-Wallet tidak cukup Saldo.
Mohon bantuannya.

Terimakasih.

**Comment by yocki-s** [comment]
Hi @bestgoodz 

Jika transaksi sudah dilakukan dan gagal dikarenakan credit card sudah overlimit. kami akan kirimkan notifikasi ke merchant dengan message = deny by bank (error code).

error code ini berasal dari bank, yang menyatakan alasan kenapa transaksi tersebut di deny.
