### ISSUE TITLE
Snap Side Slide like Demo

### ISSUE THREAD

**Issue by Magictypo** [veritrans/veritrans.github.io#81]
Pas saya coba intergrasikan snap.., muncul snapnya sebagai pop up. Bagaimana agar bisa muncul slide samping seperti pada demo?

Serta Pada Slide samping muncul detil yang lebih banyak di bandingkan dengan popup

* Oh ya halaman contact usnya juga sepertinya error makanya saya post di sini

**Comment by rizdaprasetya** [comment]
Hi @Magictypo ,

Terima kasih telah mencoba produk Midtrans. 😄 
Pada https://demo.midtrans.com page tersebut dibuat untuk men-simulasikan halaman "checkout" pada web ecommerce. Bagian yang slide-in dari samping tersebut bukan lah bagian dari Snap. Yang termasuk dalam UI Snap sendiri hanyalah payment popup yang muncul untuk melakukan pembayaran.

Anda bebas menampilkan halaman checkout anda seperti apapun pada HTML web Anda, jadi implementasi slide-in checkout summary (atau seperti apapun tampilannya) menjadi ranah Anda / web-developer untuk membuat.

> Oh ya halaman contact usnya juga sepertinya error makanya saya post di sini

Boleh diinfokan detail issue seperti apa yang dialami? Page contact-us kami bekerja dengan baik, termasuk contact formnya, hingga data yang disubmit bisa kami terima dan reply.

Thanks.

**Comment by Magictypo** [comment]
1. Berati untuk membuat slide samping seperti pada demo, apakah tetap menggunakan API Snap, atau menggunakan Core API?

2. Oh ya, saya mengalami bug ketika me request token 

```
                "item_details": [
                  {
                    "id": "ITEM1",
                    "price": 10000,
                    "quantity": 1,
                    "name": "Midtrans Bear"
                  },
                  {
                    "id": "ITEM2",
                    "price": 50000,
                    "quantity": 4,
                    "name": "Midtrans Bear"
                  },
                  {
                    "id": "ITEM3",
                    "price": 30000,
                    "quantity": 2,
                    "name": "Midtrans Bear"
                  }
                ],
```
ketika saya memasukan item_details lebih dari 1 item, API tidak mengembalikan token

3. Ketika aku coba lagi, sudah dapat berfungsi dengan baik Contact Formnya. Terima kasih atas responsenya

**Comment by rizdaprasetya** [comment]
1. Section slide in tersebut bukan bagian dari produk payment Midtrans (Snap maupun Core API), section tersebut adalah plain HTML + CSS, silahkan implementasikan di page HTML web Anda sendir.

2. Jika tidak mendapat token, bukan berarti `bug`, kemungkinan besar JSON yang dikirim mengalami `validation error`. Silahkan cek API responsenya, most likely berisi validation error message seperti ini:
```
{
    "error_messages": [
        "transaction_details.gross_amount is not equal to the sum of item_details"
    ]
}
```

Berikut contoh JSON yang valid untuk multiple item details
```
{
	"credit_card": {
		"secure": true
	},
	"transaction_details": {
		"order_id": "test-item-details-1",
		"gross_amount": 700000
	},
	"item_details": [
		{
			"id": "2",
			"price": 500000,
			"quantity": "1",
			"name": "Blouse"
		},{
			"id": "3",
			"price": 200000,
			"quantity": "1",
			"name": "Trouser"
		}
	]
}
```

Jika masih memiliki pertanyaan terkait integrasi silahkan kirim ke email: 
support [ at ] midtrans.com
Untuk mendapat response lebih cepat dan agar issue di github ini tidak out of topic.
Terima Kasih.
