### ISSUE TITLE
How to know the $VERSION-SANDBOX

### ISSUE THREAD

**Issue by j-elmer123** [veritrans/veritrans.github.io#83]
I'm trying to implement the uikit, but I can't find the `$VERSION-SANDBOX`
`compile 'com.midtrans:uikit:$VERSION-SANDBOX'`

**Comment by ziahaqi** [comment]
hi @j-elmer123 this is latest version of the sdk, so you can replace `$version` with actual version.
https://mobile-docs.midtrans.com/#latest-version
it will be like this
compile 'com.midtrans:corekit:1.9.2-SANDBOX' // for sandbox version
compile 'com.midtrans:corekit:1.9.2' // production version

**Comment by rizdaprasetya** [comment]
hi @j-elmer123 

Thanks for contacting Midtrans.
As answered, the correct version would be:
`compile 'com.midtrans:uikit:1.9.2-SANDBOX'`

Hope this resolved this issue. If you have any further question about our Mobile SDK or other products, you can email us at support@midtrans.com for faster and detailed response.

Thanks.

**Comment by j-elmer123** [comment]
Thx @rizdaprasetya @ziahaqi for the response. I thought `$VERSION-SANDBOX` and `$VERSION` using different version. like `1.9.2` and `1.9.x`
