### ISSUE TITLE
Invalid format on phone number 

### ISSUE THREAD

**Issue by ariestiyansyah** [veritrans/veritrans.github.io#84]
I got the error below while input number with symbol `()`, I tried with this number `(0274) 43434334` 

```
customer_details.billing_address.phone format is invalid format
```

But the api-docs said it accept `()` https://api-docs.midtrans.com/#customer-details

```
Customer's phone address. Minimum length is 5. Only accepts numeric and symbols +,-,(space), and (). The + symbol can only be placed in front
```

Since your documentaion allow to use `()` but your API said is invalid please let us know how to fix this one. The only thing we do to prevent this error is by using regex `^[0-9\-\+\s]*$` in telephone input validation.

Cheers

**Comment by yocki-s** [comment]
Hi @ariestiyansyah 

Terimakasih untuk informasinya. kami akan cek terlebih dahulu.

**Comment by rizdaprasetya** [comment]
Hi @ariestiyansyah ,

There was validation bug is on the frontend.
This bug has already been solved few weeks ago. Now `()` symbol are allowed.

Thanks, @yocki-s can close this issue now.
