### ISSUE TITLE
one click payment android

### ISSUE THREAD

**Issue by leonardosetiadi** [veritrans/veritrans.github.io#85]
selamat siang, saya ingin bertanya bagaimana cara mengimplement one click payment.
saya memakai versi gradle 1.9.2 dan sudah mengimplement code ini

 ```
CreditCard creditCard = new CreditCard();
creditCard.setSecure(true);
creditCard.setSaveCard(true);
transactionRequest.setCreditCard(creditCard);
```
tetapi saya masih belum bisa menyimpan credential credit card usernya. Apakah ada yang kurang dalam implementasinya?mohon bantuanny terima kasih

**Comment by yocki-s** [comment]
Hi @leonardosetiadi, 

Untuk Mobile SDK (Android) silahkan melihat dokumentasi berikut https://mobile-docs.midtrans.com/#android-sdk

Jika ada pertanyaan lagi, silahkan kirim email ke support@midtrans.com.

**Comment by yocki-s** [comment]
Hi @leonardosetiadi, 

Untuk Mobile SDK (Android) silahkan melihat dokumentasi berikut https://mobile-docs.midtrans.com/#android-sdk

Jika ada pertanyaan lagi, silahkan kirim email ke support@midtrans.com.
